### ISSUE TITLE
Missing files: deca_regs.h

### ISSUE THREAD

**Issue by bakirtasa** [br101/zephyr-dw3000-examples#2]
I cloned zephyr-dw3000-examples as well as zephyr-dw3000-decadriver, and located it under zephyr-dw3000-examples directory.
Then, I tried to build examples by using nRF Connect SDK build, however, it failed due to missing deca_regs.h file. The output from the building is in the attached file.

Then, I searched for this file in file explorer but couldn't find it anywhere. Is this file something I need to find from a different source, or my building approach is wrong? 

[dw3000 examples build error.txt](https://github.com/br101/zephyr-dw3000-examples/files/10177206/dw3000.examples.build.error.txt)

**Comment by bkx1125** [comment]
Hi,
I was able to build the project after using the example code from the bin branch and the driver from the b964a27401 branch. 
 I used the below CMake script from the ReadMe file. 
**cmake -B build -DBOARD_ROOT=. -DBOARD=nrf52dk_nrf52832 -DEXAMPLE=READING_DEV_ID  .**

Then I couldn't build the actual build directory.

I was expecting a .hex file to be able to flash the program on my device, but it generated many Visual Studio projects. 
I'm not an embedded developer so my questions might be stupid, apologize in advance, but how can I build and flash one of the examples, i.e. READING_DEV_ID to my board with the minimum afford?
I have nRF Connect SDK installed.

**Comment by br101** [comment]
Please read the getting started pages of nRF Connect SDK (https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_programming.html). If you install nRF Connect for VSCode you'll have a flash button there... Otherwise "west flash" should do that. 

Closing as this is not related to dw3000

**Comment by bkx1125** [comment]
Hi, 
I've gotten further progress. 
I was able to just build the project. Then it failed when I attempted to build the actual build directory. What is the recommended version of nRF connect SDK and CLI tools for this code? I tried to build the project by newest SDK "nRF connect v2.2.0-rc1"
Thx in advance,
